#!/bin/sh

set -x

AESD_SOCKET_PATH=${AESD_SOCKET_PATH:-/usr/bin}

HELLO_DRIVER=hello
SCULL_DRIVER=scull
FAULTY_DRIVER=faulty
AESDCHAR_DRIVER=aesdchar

case "$1" in
    start)
        cd /lib/modules/$(uname -r)
        echo "Loading the $HELLO_DRIVER driver..."
        ./module_load $HELLO_DRIVER

        echo "Loading the $FAULTY_DRIVER driver..."
        ./module_load $FAULTY_DRIVER

        echo "Loading the $SCULL_DRIVER driver..."
        ./scull_load

        echo "Loading the $AESDCHAR_DRIVER driver..."
        ./aesdchar_load
    ;;
    stop)
        cd /lib/modules/$(uname -r)
        echo "Unloading the $HELLO_DRIVER driver..."
        ./module_unload $HELLO_DRIVER

        echo "Loading the $FAULTY_DRIVER driver..."
        ./module_load $FAULTY_DRIVER

        echo "Unloading the $SCULL_DRIVER driver..."
        ./scull_unload

        echo "Unloading the $AESDCHAR_DRIVER driver..."
        ./aesdchar_unload
    ;;
    restart)
    $0 stop

    $0 start
    ;;
    *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit $?
